spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 738306367438-6hteo5abjcvcgvhan6afsdjk5vntstvp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 73dATlzLtn3BVVNvvNVl
            client-secret: YN0GtvZbVd
            scope:
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response