spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 738306367438-6hteo5abjcvcgvhan6afsdjk5vntstvp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 73dATlzLtn3BVVNvvNVl
            client-secret: YN0GtvZbVd
            scope:
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: 43be8bd02f457714b2736230b3b3a2d0
            client-secret: TftsRUMzD2Z4kXTF2MY2ta4e4xsa7Ouu
            scope:
              - profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id