spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 738306367438-6hteo5abjcvcgvhan6afsdjk5vntstvp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


logging:
  level:
    org.hibernate.SQL: debug                          # sql? logger? ?? ??
    org.hibernate.orm.jdbc.bind: trace
